### ISSUE TITLE
Track Basic app progress

### ISSUE THREAD

**Issue by salahusama** [salahusama/WorkflowStreamer-UI#49]
#### Main
- [x] Ability to create projects #32 
- [x] Ability to create tasks
- [x] Ability to edit tasks #47
- [x] Ability to move tasks across stages #7 

#### Optional
- [ ] Ability to reorder tasks #48

**Comment by salahusama** [comment]
Re-ordering tasks will require back end work, so I'll close this issue and complete this milestone. Setting an order will be similar to https://github.com/salahusama/WorkflowStreamer/issues/26
